#!/bin/bash

CURRENT_DIR="$(dirname "$0")"
ARGS=( )

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -I*) # Include directory
            INCLUDE_PATH="$(winepath -w "${1#-I}")"
            ARGS+=("-I$INCLUDE_PATH")
            shift
        ;;
        -o) # Output path
            WIN_OUTPUT_PATH="$(winepath -w "$2")"
            ARGS+=("-o" "$WIN_OUTPUT_PATH")
            shift
            shift
        ;;
        -*) # Default option
            ARGS+=("$1")
            shift
        ;;
        *) # Path argument
            PATH_ARG="$(winepath -w "$1")"
            ARGS+=("$PATH_ARG")
            shift
        ;;
    esac
done

wine "$CURRENT_DIR/qt-win32/bin/moc.exe" "${ARGS[@]}"
